# Document:
# http://simiki.org/docs/configuration.html
title: Jun's personal knowledge wiki
keywords: Technology, MachineLearning, DataMining, Wiki
description: A wiki website
author: zhang787jun
root: ./
theme: simple
debug: True
destination: output
source: content
attach: ./attach
# theme add MathJax.js
