# Document:
# http://simiki.org/docs/configuration.html

url: 
title: Jun's personal knowledge wiki
keywords: Technology, MachineLearning, DataMining, Wiki
description: A wiki website 
author: zhang787jun
root: /Wiki/
theme: simple
debug: True
destination: output
source: content
attach: attach

# theme add MathJax.js